services:
  tweet-predictor-ui:
    image: elon-tweet-predictor-ui:latest
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: elon-tweet-predictor-ui
    restart: unless-stopped
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_ENVIRONMENT: Development
      DataPath: /app/data
      TZ: America/New_York
    volumes:
      - ${PREDICTOR_DATA_PATH:-/woodpecker/src/bitbucket.org/hardcodez/elontweetpredictor/data}:/app/data
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy

      - traefik.http.routers.elon.rule=Host(`elon.incuzentric.com`)
      - traefik.http.routers.elon.entrypoints=websecure
      - traefik.http.routers.elon.tls.certresolver=le
      - traefik.http.services.elon.loadbalancer.server.port=8080

networks:
  proxy:
    external: true
